/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uh;



/**
 *
 * @author Bouguessa
 */
public class ok extends javax.swing.JFrame {

    /**
     * Creates new form ok
     */
    public ok() {
        initComponents();
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        gdetd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gdbi = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Guestiondesujets = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Guestiondesss3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        gestiondegroupe = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Evaluationc = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Evaluationf = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        stats = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jp1.setBackground(new java.awt.Color(0, 102, 102));

        gdetd.setBackground(new java.awt.Color(255, 153, 51));
        gdetd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gdetd.setName(""); // NOI18N
        gdetd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdetdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gdetdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gdetdMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gdetdMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gdetdMouseReleased(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Gestion des étudiants");
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/student-with-graduation-cap (1).png"))); // NOI18N

        javax.swing.GroupLayout gdetdLayout = new javax.swing.GroupLayout(gdetd);
        gdetd.setLayout(gdetdLayout);
        gdetdLayout.setHorizontalGroup(
            gdetdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gdetdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gdetdLayout.setVerticalGroup(
            gdetdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gdetdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gdetdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("MENU");
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));

        gdbi.setBackground(new java.awt.Color(255, 153, 51));
        gdbi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gdbi.setName(""); // NOI18N
        gdbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdbiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gdbiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gdbiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gdbiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gdbiMouseReleased(evt);
            }
        });

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Gestion des binômes");
        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/couple-users-silhouette.png"))); // NOI18N

        javax.swing.GroupLayout gdbiLayout = new javax.swing.GroupLayout(gdbi);
        gdbi.setLayout(gdbiLayout);
        gdbiLayout.setHorizontalGroup(
            gdbiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gdbiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        gdbiLayout.setVerticalGroup(
            gdbiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gdbiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Guestiondesujets.setBackground(new java.awt.Color(255, 153, 51));
        Guestiondesujets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guestiondesujets.setName(""); // NOI18N
        Guestiondesujets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuestiondesujetsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuestiondesujetsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuestiondesujetsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GuestiondesujetsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GuestiondesujetsMouseReleased(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Gestion des sujets");
        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/file.png"))); // NOI18N

        javax.swing.GroupLayout GuestiondesujetsLayout = new javax.swing.GroupLayout(Guestiondesujets);
        Guestiondesujets.setLayout(GuestiondesujetsLayout);
        GuestiondesujetsLayout.setHorizontalGroup(
            GuestiondesujetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestiondesujetsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GuestiondesujetsLayout.setVerticalGroup(
            GuestiondesujetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuestiondesujetsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuestiondesujetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Guestiondesss3.setBackground(new java.awt.Color(255, 153, 51));
        Guestiondesss3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guestiondesss3.setName(""); // NOI18N
        Guestiondesss3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Guestiondesss3MouseMoved(evt);
            }
        });
        Guestiondesss3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guestiondesss3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Guestiondesss3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Guestiondesss3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Guestiondesss3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Guestiondesss3MouseReleased(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Gestion des séances");
        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/audience-in-presentation-of-business.png"))); // NOI18N

        javax.swing.GroupLayout Guestiondesss3Layout = new javax.swing.GroupLayout(Guestiondesss3);
        Guestiondesss3.setLayout(Guestiondesss3Layout);
        Guestiondesss3Layout.setHorizontalGroup(
            Guestiondesss3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Guestiondesss3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Guestiondesss3Layout.setVerticalGroup(
            Guestiondesss3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Guestiondesss3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Guestiondesss3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        gestiondegroupe.setBackground(new java.awt.Color(255, 153, 51));
        gestiondegroupe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gestiondegroupe.setName(""); // NOI18N
        gestiondegroupe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gestiondegroupeMouseMoved(evt);
            }
        });
        gestiondegroupe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestiondegroupeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gestiondegroupeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gestiondegroupeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestiondegroupeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gestiondegroupeMouseReleased(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Gestion des groupes");
        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/users-group.png"))); // NOI18N

        javax.swing.GroupLayout gestiondegroupeLayout = new javax.swing.GroupLayout(gestiondegroupe);
        gestiondegroupe.setLayout(gestiondegroupeLayout);
        gestiondegroupeLayout.setHorizontalGroup(
            gestiondegroupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestiondegroupeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gestiondegroupeLayout.setVerticalGroup(
            gestiondegroupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestiondegroupeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestiondegroupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Evaluationc.setBackground(new java.awt.Color(255, 153, 51));
        Evaluationc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Evaluationc.setName(""); // NOI18N
        Evaluationc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EvaluationcMouseMoved(evt);
            }
        });
        Evaluationc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EvaluationcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EvaluationcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EvaluationcMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EvaluationcMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EvaluationcMouseReleased(evt);
            }
        });

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Evaluation continue");
        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/roundabout.png"))); // NOI18N

        javax.swing.GroupLayout EvaluationcLayout = new javax.swing.GroupLayout(Evaluationc);
        Evaluationc.setLayout(EvaluationcLayout);
        EvaluationcLayout.setHorizontalGroup(
            EvaluationcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EvaluationcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        EvaluationcLayout.setVerticalGroup(
            EvaluationcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvaluationcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EvaluationcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Evaluationf.setBackground(new java.awt.Color(255, 153, 51));
        Evaluationf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Evaluationf.setName(""); // NOI18N
        Evaluationf.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EvaluationfMouseMoved(evt);
            }
        });
        Evaluationf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EvaluationfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EvaluationfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EvaluationfMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EvaluationfMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EvaluationfMouseReleased(evt);
            }
        });

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Evaluation Finale");
        jLabel36.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/petroleum-solvent.png"))); // NOI18N

        javax.swing.GroupLayout EvaluationfLayout = new javax.swing.GroupLayout(Evaluationf);
        Evaluationf.setLayout(EvaluationfLayout);
        EvaluationfLayout.setHorizontalGroup(
            EvaluationfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EvaluationfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        EvaluationfLayout.setVerticalGroup(
            EvaluationfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvaluationfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EvaluationfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        stats.setBackground(new java.awt.Color(255, 153, 51));
        stats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stats.setName(""); // NOI18N
        stats.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                statsMouseMoved(evt);
            }
        });
        stats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statsMouseReleased(evt);
            }
        });

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Statistiques");
        jLabel38.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgspackage/statistics.png"))); // NOI18N

        javax.swing.GroupLayout statsLayout = new javax.swing.GroupLayout(stats);
        stats.setLayout(statsLayout);
        statsLayout.setHorizontalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statsLayout.setVerticalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Guestiondesujets, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gdetd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gdbi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(gestiondegroupe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Evaluationc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guestiondesss3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Evaluationf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(322, 322, 322))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gdetd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guestiondesss3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Evaluationf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gdbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestiondegroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Evaluationc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guestiondesujets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void gdetdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdetdMouseEntered
gdetd.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_gdetdMouseEntered

    private void gdetdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdetdMouseExited
      gdetd.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_gdetdMouseExited

    private void gdetdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdetdMouseReleased
        // TODO add your handling code here:
         gdetd.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_gdetdMouseReleased

    private void gdetdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdetdMouseClicked
    Etudiants p0 = new Etudiants();
    p0.setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_gdetdMouseClicked

    private void gdetdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdetdMousePressed
        // TODO add your handling code here: 219,98,0
      gdetd.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_gdetdMousePressed

    private void gdbiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdbiMouseClicked
        bi12 p1 = new bi12();
        p1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gdbiMouseClicked

    private void gdbiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdbiMouseEntered
        gdbi.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_gdbiMouseEntered

    private void gdbiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdbiMouseExited
        gdbi.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_gdbiMouseExited

    private void gdbiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdbiMousePressed
      
        gdbi.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_gdbiMousePressed

    private void gdbiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdbiMouseReleased
        // TODO add your handling code here:
        gdbi.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_gdbiMouseReleased

    private void GuestiondesujetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestiondesujetsMouseClicked
        Sujets12 p8 = new Sujets12();
        p8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GuestiondesujetsMouseClicked

    private void GuestiondesujetsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestiondesujetsMouseEntered
        Guestiondesujets.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_GuestiondesujetsMouseEntered

    private void GuestiondesujetsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestiondesujetsMouseExited
        Guestiondesujets.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_GuestiondesujetsMouseExited

    private void GuestiondesujetsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestiondesujetsMousePressed
        // TODO add your handling code here: 219,98,0
        Guestiondesujets.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_GuestiondesujetsMousePressed

    private void GuestiondesujetsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestiondesujetsMouseReleased
        // TODO add your handling code here:
        Guestiondesujets.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_GuestiondesujetsMouseReleased

    private void Guestiondesss3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guestiondesss3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Guestiondesss3MouseMoved

    private void Guestiondesss3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guestiondesss3MouseClicked
        sss12 p8 = new sss12();
        p8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Guestiondesss3MouseClicked

    private void Guestiondesss3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guestiondesss3MouseEntered
        Guestiondesss3.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_Guestiondesss3MouseEntered

    private void Guestiondesss3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guestiondesss3MouseExited
        Guestiondesss3.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_Guestiondesss3MouseExited

    private void Guestiondesss3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guestiondesss3MousePressed
        // TODO add your handling code here: 219,98,0
        Guestiondesss3.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_Guestiondesss3MousePressed

    private void Guestiondesss3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guestiondesss3MouseReleased
        // TODO add your handling code here:
        Guestiondesss3.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_Guestiondesss3MouseReleased

    private void gestiondegroupeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestiondegroupeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_gestiondegroupeMouseMoved

    private void gestiondegroupeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestiondegroupeMouseClicked
        grp p8 = new grp();
        p8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestiondegroupeMouseClicked

    private void gestiondegroupeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestiondegroupeMouseEntered
        gestiondegroupe.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_gestiondegroupeMouseEntered

    private void gestiondegroupeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestiondegroupeMouseExited
        gestiondegroupe.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_gestiondegroupeMouseExited

    private void gestiondegroupeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestiondegroupeMousePressed
        // TODO add your handling code here: 219,98,0
        gestiondegroupe.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_gestiondegroupeMousePressed

    private void gestiondegroupeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestiondegroupeMouseReleased
        // TODO add your handling code here:
        gestiondegroupe.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_gestiondegroupeMouseReleased

    private void EvaluationcMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationcMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_EvaluationcMouseMoved

    private void EvaluationcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationcMouseClicked
        EvaCon p8 = new EvaCon();
        p8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EvaluationcMouseClicked

    private void EvaluationcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationcMouseEntered
        Evaluationc.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_EvaluationcMouseEntered

    private void EvaluationcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationcMouseExited
        Evaluationc.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_EvaluationcMouseExited

    private void EvaluationcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationcMousePressed
        // TODO add your handling code here: 219,98,0
        Evaluationc.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_EvaluationcMousePressed

    private void EvaluationcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationcMouseReleased
        // TODO add your handling code here:
        Evaluationc.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_EvaluationcMouseReleased

    private void EvaluationfMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationfMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_EvaluationfMouseMoved

    private void EvaluationfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationfMouseClicked
        EvaF p11 = new EvaF();
        p11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EvaluationfMouseClicked

    private void EvaluationfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationfMouseEntered
        Evaluationf.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_EvaluationfMouseEntered

    private void EvaluationfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationfMouseExited
        Evaluationf.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_EvaluationfMouseExited

    private void EvaluationfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationfMousePressed
        // TODO add your handling code here: 219,98,0
        Evaluationf.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_EvaluationfMousePressed

    private void EvaluationfMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluationfMouseReleased
        // TODO add your handling code here:
        Evaluationf.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_EvaluationfMouseReleased

    private void statsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_statsMouseMoved

    private void statsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMouseClicked
        statistics p8 = new statistics();
        p8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_statsMouseClicked

    private void statsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMouseEntered
        stats.setBackground(new java.awt.Color(255,184,79));        // TODO add your handling code here:
    }//GEN-LAST:event_statsMouseEntered

    private void statsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMouseExited
        stats.setBackground(new java.awt.Color(255,153,51));  // TODO add your handling code here:
    }//GEN-LAST:event_statsMouseExited

    private void statsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMousePressed
        // TODO add your handling code here: 219,98,0
        stats.setBackground(new java.awt.Color(219,98,0));
    }//GEN-LAST:event_statsMousePressed

    private void statsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsMouseReleased
        // TODO add your handling code here:
        stats.setBackground(new java.awt.Color(255,184,79));
    }//GEN-LAST:event_statsMouseReleased

        
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ok().setVisible(true);
            }
        });
        
      
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Evaluationc;
    private javax.swing.JPanel Evaluationf;
    private javax.swing.JPanel Guestiondesss3;
    private javax.swing.JPanel Guestiondesujets;
    private javax.swing.JPanel gdbi;
    private javax.swing.JPanel gdetd;
    private javax.swing.JPanel gestiondegroupe;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel stats;
    // End of variables declaration//GEN-END:variables
}
